class ChangeColumnsInVisit < ActiveRecord::Migration
  def self.up
    change_column(:visits, :donor_id, :integer, {:null => false})
    change_column(:visits, :card_number, :string, {:limit => 30, :null => false})
    change_column(:visits, :reg_date, :date, {:null => false})
    change_column(:visits, :code_org, :decimal, {:precision => 10, :scale => 0, :null => false})
    change_column(:visits, :reception_id, :integer, {:null => false})
    change_column(:visits, :visit_date, :date, {:null => false})
    change_column(:visits, :target_id, :integer, {:null => false})
    change_column(:visits, :type_payment, :boolean, {:null => false})
    change_column(:visits, :blood_for_id, :integer, {:null => false})
    change_column(:visits, :type_donation, :string, {:limit => 50})
    change_column(:visits, :blood_group_id, :integer, {:null => false})
    change_column(:visits, :rh_factor_id, :integer, {:null => false})
    change_column(:visits, :donor_name, :string, {:limit => 100, :null => false})
    change_column(:visits, :gender, :boolean, {:null => false})
    change_column(:visits, :age, :decimal, {:precision => 3, :scale => 0, :null => false})
    change_column(:visits, :post_code, :string, {:limit => 20})
    change_column(:visits, :address, :string, {:limit => 100})
    change_column(:visits, :work, :string, {:limit => 100})
    change_column(:visits, :job, :string, {:limit => 100})
    change_column(:visits, :reg_name_id, :integer, {:null => false})
    change_column(:visits, :control_blood_id, :integer, {:null => false})
    change_column(:visits, :hbs, :decimal, {:precision => 5, :scale => 0, :null => false})
    change_column(:visits, :analysis_date, :date, {:null => false})
    change_column(:visits, :doctor_test_id, :integer, {:null => false})
    change_column(:visits, :ill_hepatitis, :boolean, {:null => false})
    change_column(:visits, :ill_tb, :boolean, {:null => false})
    change_column(:visits, :ill_syphilis, :boolean, {:null => false})
    change_column(:visits, :ill_mal, :boolean, {:null => false})
    change_column(:visits, :operation, :boolean, {:null => false})
    change_column(:visits, :transfusion, :boolean, {:null => false})
    change_column(:visits, :infection, :boolean, {:null => false})
    change_column(:visits, :dermis, :boolean, {:null => false})
    change_column(:visits, :dermis_doctor, :boolean, {:null => false})
    change_column(:visits, :doctor_skin_id, :integer, {:null => false})
    change_column(:visits, :pulse, :decimal, {:precision => 3, :scale => 0})
    change_column(:visits, :sys_pressure, :decimal, {:precision => 3, :scale => 0})
    change_column(:visits, :dias_pressure, :decimal, {:precision => 3, :scale => 0})
    change_column(:visits, :allow_amount, :decimal, {:precision => 3, :scale => 0, :null => false})
    change_column(:visits, :therapist_doctor, :boolean, {:null => false})
    change_column(:visits, :doctor_therapist_id, :integer, {:null => false})
    change_column(:visits, :date_donation, :date, {:null => false})
    change_column(:visits, :doctor_donation_id, :integer, {:null => false})
    change_column(:visits, :donation_mode_id, :integer, {:null => false})
    change_column(:visits, :donation_type_id, :integer, {:null => false})
    change_column(:visits, :amount_probe, :decimal, {:precision => 3, :scale => 0, :null => false})
    change_column(:visits, :amount_dose, :decimal, {:precision => 3, :scale => 0, :null => false})
    change_column(:visits, :type_packing_id, :integer, {:null => false})
    change_column(:visits, :bottle_number, :string, {:limit => 30, :null => false})
    change_column(:visits, :inspect_bilirubin, :decimal, {:precision => 5, :scale => 0, :null => false})
    change_column(:visits, :inspect_alt, :decimal, {:precision => 5, :scale => 0, :null => false})
    change_column(:visits, :inspect_syphilis, :boolean, {:null => false})
    change_column(:visits, :date_syphilis, :date, {:null => false})
    change_column(:visits, :inspect_hep_c, :boolean, {:null => false})
    change_column(:visits, :date_hep_c, :date, {:null => false})
    change_column(:visits, :inspect_hep_b, :boolean, {:null => false})
    change_column(:visits, :date_hep_b, :date, {:null => false})
    change_column(:visits, :inspect_aids, :boolean, {:null => false})
    change_column(:visits, :date_aids, :date, {:null => false})
  end
end